// Code generated by protoc-gen-tarp. DO NOT EDIT. haberdasher

import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:protobuf/protobuf.dart';
import 'package:tart/tart.dart' as twirp;
import 'haberdasher.pb.dart';
import 'suit.pb.dart';


/// Haberdasher service makes hats for clients.
abstract class Haberdasher {
  /// MakeHat produces a hat of mysterious, randomly-selected color!
  Future<Hat> makeHat(twirp.Context ctx, Size req);
  /// MakeSuit produces a suit of perfect proportions, with random color
  Future<Suit> makeSuit(twirp.Context ctx, SuitSizeReq req);
}

/// Haberdasher service makes hats for clients.
class HaberdasherJSONClient implements Haberdasher {
  String baseUrl;
  String prefix;
  late twirp.ClientHooks hooks;
  late twirp.Interceptor interceptor;

  HaberdasherJSONClient(this.baseUrl, this.prefix, {twirp.ClientHooks? hooks, twirp.Interceptor? interceptor}) {
    if (!baseUrl.endsWith('/')) baseUrl += '/';
    if (!prefix.endsWith('/')) prefix += '/';
    if (prefix.startsWith('/')) prefix = prefix.substring(1);

    this.hooks = hooks ?? twirp.ClientHooks();
    this.interceptor = interceptor ?? twirp.chainInterceptor([]);
  }

  @override
  Future<Hat> makeHat(twirp.Context ctx, Size req) async {
    ctx = twirp.withPackageName(ctx, 'protos');
    ctx = twirp.withServiceName(ctx, 'Haberdasher');
    ctx = twirp.withMethodName(ctx, 'MakeHat');
    return interceptor((ctx, req) {
      return callMakeHat(ctx, req);
    })(ctx, req);
  }

  Future<Hat> callMakeHat(twirp.Context ctx, Size req) async {
    try {
      Uri url = Uri.parse(baseUrl + prefix + 'protos.Haberdasher/MakeHat');
      final data = await doJSONRequest(ctx, url, hooks, req);
      final Hat res = Hat.create();
      res.mergeFromProto3Json(json.decode(data));
      return Future.value(res);
    } catch (e) {
      rethrow;
    }
  }

  @override
  Future<Suit> makeSuit(twirp.Context ctx, SuitSizeReq req) async {
    ctx = twirp.withPackageName(ctx, 'protos');
    ctx = twirp.withServiceName(ctx, 'Haberdasher');
    ctx = twirp.withMethodName(ctx, 'MakeSuit');
    return interceptor((ctx, req) {
      return callMakeSuit(ctx, req);
    })(ctx, req);
  }

  Future<Suit> callMakeSuit(twirp.Context ctx, SuitSizeReq req) async {
    try {
      Uri url = Uri.parse(baseUrl + prefix + 'protos.Haberdasher/MakeSuit');
      final data = await doJSONRequest(ctx, url, hooks, req);
      final Suit res = Suit.create();
      res.mergeFromProto3Json(json.decode(data));
      return Future.value(res);
    } catch (e) {
      rethrow;
    }
  }
}

/// Haberdasher service makes hats for clients.
class HaberdasherProtobufClient implements Haberdasher {
  String baseUrl;
  String prefix;
  late twirp.ClientHooks hooks;
  late twirp.Interceptor interceptor;

  HaberdasherProtobufClient(this.baseUrl, this.prefix, {twirp.ClientHooks? hooks, twirp.Interceptor? interceptor}) {
    if (!baseUrl.endsWith('/')) baseUrl += '/';
    if (!prefix.endsWith('/')) prefix += '/';
    if (prefix.startsWith('/')) prefix = prefix.substring(1);

    this.hooks = hooks ?? twirp.ClientHooks();
    this.interceptor = interceptor ?? twirp.chainInterceptor([]);
  }

  @override
  Future<Hat> makeHat(twirp.Context ctx, Size req) async {
    ctx = twirp.withPackageName(ctx, 'protos');
    ctx = twirp.withServiceName(ctx, 'Haberdasher');
    ctx = twirp.withMethodName(ctx, 'MakeHat');
    return interceptor((ctx, req) {
      return callMakeHat(ctx, req);
    })(ctx, req);
  }

  Future<Hat> callMakeHat(twirp.Context ctx, Size req) async {
    try {
      Uri url = Uri.parse(baseUrl + prefix + 'protos.Haberdasher/MakeHat');
      final data = await doProtobufRequest(ctx, url, hooks, req);
      final Hat res = Hat.create();
      res.mergeFromBuffer(data);
      return Future.value(res);
    } catch (e) {
      rethrow;
    }
  }

  @override
  Future<Suit> makeSuit(twirp.Context ctx, SuitSizeReq req) async {
    ctx = twirp.withPackageName(ctx, 'protos');
    ctx = twirp.withServiceName(ctx, 'Haberdasher');
    ctx = twirp.withMethodName(ctx, 'MakeSuit');
    return interceptor((ctx, req) {
      return callMakeSuit(ctx, req);
    })(ctx, req);
  }

  Future<Suit> callMakeSuit(twirp.Context ctx, SuitSizeReq req) async {
    try {
      Uri url = Uri.parse(baseUrl + prefix + 'protos.Haberdasher/MakeSuit');
      final data = await doProtobufRequest(ctx, url, hooks, req);
      final Suit res = Suit.create();
      res.mergeFromBuffer(data);
      return Future.value(res);
    } catch (e) {
      rethrow;
    }
  }
}

Future<List<int>> doProtobufRequest(twirp.Context ctx, Uri url,
    twirp.ClientHooks hooks, GeneratedMessage msgReq) async {
  // setup http client
  final httpClient = http.Client();

  try {
    // create http request
    final req = createRequest(url, ctx, 'application/protobuf');

    // add request data to body
    req.bodyBytes = msgReq.writeToBuffer();

    // call onRequestPrepared hook for user to modify request
    ctx = hooks.onRequestPrepared(ctx, req);

    // send data
    final res = await httpClient.send(req);

    // if success, parse and return response
    if (res.statusCode == 200) {
      List<int> data = <int>[];
      await res.stream.listen((value) {
        data.addAll(value);
      }).asFuture();
      hooks.onResponseReceived(ctx);
      return Future.value(data);
    }

    // we received a twirp related error
    throw twirp.Error.fromJson(
        json.decode(await res.stream.transform(utf8.decoder).join()));
  } on twirp.Error catch (twirpErr) {
    hooks.onError(ctx, twirpErr);
    rethrow;
  } catch (e) {
    // catch http connection error or from onRequestPrepared
    final twirpErr = twirp.Error.fromConnectionError(e.toString());
    hooks.onError(ctx, twirpErr);
    throw twirpErr;
  } finally {
    httpClient.close();
  }
}

Future<String> doJSONRequest(twirp.Context ctx, Uri url,
    twirp.ClientHooks hooks, GeneratedMessage msgReq) async {
  // setup http client
  final httpClient = http.Client();

  try {
    // create http request
    final req = createRequest(url, ctx, 'application/json');

    // add request data to body
    req.body = json.encode(msgReq.toProto3Json());

    // call onRequestPrepared hook for user to modify request
    ctx = hooks.onRequestPrepared(ctx, req);

    // send data
    final res = await httpClient.send(req);

    // if success, parse and return response
    if (res.statusCode == 200) {
      final data = await res.stream.transform(utf8.decoder).join().then((data) {
        hooks.onResponseReceived(ctx);
        return data;
      });
      return Future.value(data);
    }

    // we received a twirp related error
    throw twirp.Error.fromJson(
        json.decode(await res.stream.transform(utf8.decoder).join()));
  } on twirp.Error catch (twirpErr) {
    hooks.onError(ctx, twirpErr);
    rethrow;
  } catch (e) {
    // catch http connection error
    final twirpErr = twirp.Error.fromConnectionError(e.toString());
    hooks.onError(ctx, twirpErr);
    throw twirpErr;
  } finally {
    httpClient.close();
  }
}

http.Request createRequest(
    Uri url, twirp.Context ctx, String applicationHeader) {
  // setup request
  final req = http.Request("POST", url);

  // add headers from context
  final headersFromCtx = twirp.retrieveHttpRequestHeaders(ctx) ?? {};
  req.headers.addAll(headersFromCtx);

  // add required headers
  req.headers['Accept'] = applicationHeader;
  req.headers['Content-Type'] = applicationHeader;

  return req;
}
