// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: haberdasher.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Size of a Hat, in inches.
type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inches        int32                  `protobuf:"varint,1,opt,name=inches,proto3" json:"inches,omitempty"` // must be > 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_haberdasher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_haberdasher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_haberdasher_proto_rawDescGZIP(), []int{0}
}

func (x *Size) GetInches() int32 {
	if x != nil {
		return x.Inches
	}
	return 0
}

// A Hat is a piece of headwear made by a Haberdasher.
type Hat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inches        int32                  `protobuf:"varint,1,opt,name=inches,proto3" json:"inches,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"` // anything but "invisible"
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`   // i.e. "bowler"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hat) Reset() {
	*x = Hat{}
	mi := &file_haberdasher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hat) ProtoMessage() {}

func (x *Hat) ProtoReflect() protoreflect.Message {
	mi := &file_haberdasher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hat.ProtoReflect.Descriptor instead.
func (*Hat) Descriptor() ([]byte, []int) {
	return file_haberdasher_proto_rawDescGZIP(), []int{1}
}

func (x *Hat) GetInches() int32 {
	if x != nil {
		return x.Inches
	}
	return 0
}

func (x *Hat) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Hat) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_haberdasher_proto protoreflect.FileDescriptor

const file_haberdasher_proto_rawDesc = "" +
	"\n" +
	"\x11haberdasher.proto\x12\x06protos\x1a\n" +
	"suit.proto\"\x1e\n" +
	"\x04Size\x12\x16\n" +
	"\x06inches\x18\x01 \x01(\x05R\x06inches\"G\n" +
	"\x03Hat\x12\x16\n" +
	"\x06inches\x18\x01 \x01(\x05R\x06inches\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name2b\n" +
	"\vHaberdasher\x12$\n" +
	"\aMakeHat\x12\f.protos.Size\x1a\v.protos.Hat\x12-\n" +
	"\bMakeSuit\x12\x13.protos.SuitSizeReq\x1a\f.protos.SuitB)Z'github.com/syncapod/tart/example/protosb\x06proto3"

var (
	file_haberdasher_proto_rawDescOnce sync.Once
	file_haberdasher_proto_rawDescData []byte
)

func file_haberdasher_proto_rawDescGZIP() []byte {
	file_haberdasher_proto_rawDescOnce.Do(func() {
		file_haberdasher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_haberdasher_proto_rawDesc), len(file_haberdasher_proto_rawDesc)))
	})
	return file_haberdasher_proto_rawDescData
}

var file_haberdasher_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_haberdasher_proto_goTypes = []any{
	(*Size)(nil),        // 0: protos.Size
	(*Hat)(nil),         // 1: protos.Hat
	(*SuitSizeReq)(nil), // 2: protos.SuitSizeReq
	(*Suit)(nil),        // 3: protos.Suit
}
var file_haberdasher_proto_depIdxs = []int32{
	0, // 0: protos.Haberdasher.MakeHat:input_type -> protos.Size
	2, // 1: protos.Haberdasher.MakeSuit:input_type -> protos.SuitSizeReq
	1, // 2: protos.Haberdasher.MakeHat:output_type -> protos.Hat
	3, // 3: protos.Haberdasher.MakeSuit:output_type -> protos.Suit
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_haberdasher_proto_init() }
func file_haberdasher_proto_init() {
	if File_haberdasher_proto != nil {
		return
	}
	file_suit_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_haberdasher_proto_rawDesc), len(file_haberdasher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_haberdasher_proto_goTypes,
		DependencyIndexes: file_haberdasher_proto_depIdxs,
		MessageInfos:      file_haberdasher_proto_msgTypes,
	}.Build()
	File_haberdasher_proto = out.File
	file_haberdasher_proto_goTypes = nil
	file_haberdasher_proto_depIdxs = nil
}
