// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: suit.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SuitSize int32

const (
	SuitSize_SM SuitSize = 0
	SuitSize_MD SuitSize = 1
	SuitSize_LG SuitSize = 2
	SuitSize_XL SuitSize = 3
)

// Enum value maps for SuitSize.
var (
	SuitSize_name = map[int32]string{
		0: "SM",
		1: "MD",
		2: "LG",
		3: "XL",
	}
	SuitSize_value = map[string]int32{
		"SM": 0,
		"MD": 1,
		"LG": 2,
		"XL": 3,
	}
)

func (x SuitSize) Enum() *SuitSize {
	p := new(SuitSize)
	*p = x
	return p
}

func (x SuitSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SuitSize) Descriptor() protoreflect.EnumDescriptor {
	return file_suit_proto_enumTypes[0].Descriptor()
}

func (SuitSize) Type() protoreflect.EnumType {
	return &file_suit_proto_enumTypes[0]
}

func (x SuitSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SuitSize.Descriptor instead.
func (SuitSize) EnumDescriptor() ([]byte, []int) {
	return file_suit_proto_rawDescGZIP(), []int{0}
}

type SuitSizeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          SuitSize               `protobuf:"varint,1,opt,name=size,proto3,enum=protos.SuitSize" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuitSizeReq) Reset() {
	*x = SuitSizeReq{}
	mi := &file_suit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuitSizeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuitSizeReq) ProtoMessage() {}

func (x *SuitSizeReq) ProtoReflect() protoreflect.Message {
	mi := &file_suit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuitSizeReq.ProtoReflect.Descriptor instead.
func (*SuitSizeReq) Descriptor() ([]byte, []int) {
	return file_suit_proto_rawDescGZIP(), []int{0}
}

func (x *SuitSizeReq) GetSize() SuitSize {
	if x != nil {
		return x.Size
	}
	return SuitSize_SM
}

type Suit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          SuitSize               `protobuf:"varint,1,opt,name=size,proto3,enum=protos.SuitSize" json:"size,omitempty"`
	Color         string                 `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Suit) Reset() {
	*x = Suit{}
	mi := &file_suit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suit) ProtoMessage() {}

func (x *Suit) ProtoReflect() protoreflect.Message {
	mi := &file_suit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suit.ProtoReflect.Descriptor instead.
func (*Suit) Descriptor() ([]byte, []int) {
	return file_suit_proto_rawDescGZIP(), []int{1}
}

func (x *Suit) GetSize() SuitSize {
	if x != nil {
		return x.Size
	}
	return SuitSize_SM
}

func (x *Suit) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

var File_suit_proto protoreflect.FileDescriptor

const file_suit_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"suit.proto\x12\x06protos\"3\n" +
	"\vSuitSizeReq\x12$\n" +
	"\x04size\x18\x01 \x01(\x0e2\x10.protos.SuitSizeR\x04size\"B\n" +
	"\x04Suit\x12$\n" +
	"\x04size\x18\x01 \x01(\x0e2\x10.protos.SuitSizeR\x04size\x12\x14\n" +
	"\x05color\x18\x02 \x01(\tR\x05color**\n" +
	"\bSuitSize\x12\x06\n" +
	"\x02SM\x10\x00\x12\x06\n" +
	"\x02MD\x10\x01\x12\x06\n" +
	"\x02LG\x10\x02\x12\x06\n" +
	"\x02XL\x10\x03B)Z'github.com/syncapod/tart/example/protosb\x06proto3"

var (
	file_suit_proto_rawDescOnce sync.Once
	file_suit_proto_rawDescData []byte
)

func file_suit_proto_rawDescGZIP() []byte {
	file_suit_proto_rawDescOnce.Do(func() {
		file_suit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_suit_proto_rawDesc), len(file_suit_proto_rawDesc)))
	})
	return file_suit_proto_rawDescData
}

var file_suit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_suit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_suit_proto_goTypes = []any{
	(SuitSize)(0),       // 0: protos.SuitSize
	(*SuitSizeReq)(nil), // 1: protos.SuitSizeReq
	(*Suit)(nil),        // 2: protos.Suit
}
var file_suit_proto_depIdxs = []int32{
	0, // 0: protos.SuitSizeReq.size:type_name -> protos.SuitSize
	0, // 1: protos.Suit.size:type_name -> protos.SuitSize
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_suit_proto_init() }
func file_suit_proto_init() {
	if File_suit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_suit_proto_rawDesc), len(file_suit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_suit_proto_goTypes,
		DependencyIndexes: file_suit_proto_depIdxs,
		EnumInfos:         file_suit_proto_enumTypes,
		MessageInfos:      file_suit_proto_msgTypes,
	}.Build()
	File_suit_proto = out.File
	file_suit_proto_goTypes = nil
	file_suit_proto_depIdxs = nil
}
