// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: suit.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SuitSize int32

const (
	SuitSize_SM SuitSize = 0
	SuitSize_MD SuitSize = 1
	SuitSize_LG SuitSize = 2
	SuitSize_XL SuitSize = 3
)

// Enum value maps for SuitSize.
var (
	SuitSize_name = map[int32]string{
		0: "SM",
		1: "MD",
		2: "LG",
		3: "XL",
	}
	SuitSize_value = map[string]int32{
		"SM": 0,
		"MD": 1,
		"LG": 2,
		"XL": 3,
	}
)

func (x SuitSize) Enum() *SuitSize {
	p := new(SuitSize)
	*p = x
	return p
}

func (x SuitSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SuitSize) Descriptor() protoreflect.EnumDescriptor {
	return file_suit_proto_enumTypes[0].Descriptor()
}

func (SuitSize) Type() protoreflect.EnumType {
	return &file_suit_proto_enumTypes[0]
}

func (x SuitSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SuitSize.Descriptor instead.
func (SuitSize) EnumDescriptor() ([]byte, []int) {
	return file_suit_proto_rawDescGZIP(), []int{0}
}

type SuitSizeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size SuitSize `protobuf:"varint,1,opt,name=size,proto3,enum=protos.SuitSize" json:"size,omitempty"`
}

func (x *SuitSizeReq) Reset() {
	*x = SuitSizeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuitSizeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuitSizeReq) ProtoMessage() {}

func (x *SuitSizeReq) ProtoReflect() protoreflect.Message {
	mi := &file_suit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuitSizeReq.ProtoReflect.Descriptor instead.
func (*SuitSizeReq) Descriptor() ([]byte, []int) {
	return file_suit_proto_rawDescGZIP(), []int{0}
}

func (x *SuitSizeReq) GetSize() SuitSize {
	if x != nil {
		return x.Size
	}
	return SuitSize_SM
}

type Suit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Size  SuitSize `protobuf:"varint,1,opt,name=size,proto3,enum=protos.SuitSize" json:"size,omitempty"`
	Color string   `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
}

func (x *Suit) Reset() {
	*x = Suit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_suit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Suit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suit) ProtoMessage() {}

func (x *Suit) ProtoReflect() protoreflect.Message {
	mi := &file_suit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suit.ProtoReflect.Descriptor instead.
func (*Suit) Descriptor() ([]byte, []int) {
	return file_suit_proto_rawDescGZIP(), []int{1}
}

func (x *Suit) GetSize() SuitSize {
	if x != nil {
		return x.Size
	}
	return SuitSize_SM
}

func (x *Suit) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

var File_suit_proto protoreflect.FileDescriptor

var file_suit_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x73, 0x75, 0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x22, 0x33, 0x0a, 0x0b, 0x53, 0x75, 0x69, 0x74, 0x53, 0x69, 0x7a, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x24, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x75, 0x69, 0x74, 0x53,
	0x69, 0x7a, 0x65, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x22, 0x42, 0x0a, 0x04, 0x53, 0x75, 0x69,
	0x74, 0x12, 0x24, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x53, 0x75, 0x69, 0x74, 0x53, 0x69, 0x7a,
	0x65, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x6c, 0x6f, 0x72, 0x2a, 0x2a, 0x0a,
	0x08, 0x53, 0x75, 0x69, 0x74, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x53, 0x4d, 0x10,
	0x00, 0x12, 0x06, 0x0a, 0x02, 0x4d, 0x44, 0x10, 0x01, 0x12, 0x06, 0x0a, 0x02, 0x4c, 0x47, 0x10,
	0x02, 0x12, 0x06, 0x0a, 0x02, 0x58, 0x4c, 0x10, 0x03, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x79, 0x6e, 0x63, 0x61, 0x70, 0x6f, 0x64,
	0x2f, 0x74, 0x61, 0x72, 0x74, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_suit_proto_rawDescOnce sync.Once
	file_suit_proto_rawDescData = file_suit_proto_rawDesc
)

func file_suit_proto_rawDescGZIP() []byte {
	file_suit_proto_rawDescOnce.Do(func() {
		file_suit_proto_rawDescData = protoimpl.X.CompressGZIP(file_suit_proto_rawDescData)
	})
	return file_suit_proto_rawDescData
}

var file_suit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_suit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_suit_proto_goTypes = []interface{}{
	(SuitSize)(0),       // 0: protos.SuitSize
	(*SuitSizeReq)(nil), // 1: protos.SuitSizeReq
	(*Suit)(nil),        // 2: protos.Suit
}
var file_suit_proto_depIdxs = []int32{
	0, // 0: protos.SuitSizeReq.size:type_name -> protos.SuitSize
	0, // 1: protos.Suit.size:type_name -> protos.SuitSize
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_suit_proto_init() }
func file_suit_proto_init() {
	if File_suit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_suit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuitSizeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_suit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Suit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_suit_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_suit_proto_goTypes,
		DependencyIndexes: file_suit_proto_depIdxs,
		EnumInfos:         file_suit_proto_enumTypes,
		MessageInfos:      file_suit_proto_msgTypes,
	}.Build()
	File_suit_proto = out.File
	file_suit_proto_rawDesc = nil
	file_suit_proto_goTypes = nil
	file_suit_proto_depIdxs = nil
}
