name: tart
description: tart is a Twirp library for Dart. This is to be used in conjunction with protoc-gen-tart. https://github.com/syncapod/tart
version: 0.5.1
homepage: https://github.com/syncapod/tart

environment:
  sdk: ">=2.15.1 <4.0.0"

dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.20.1
