name: tart
description: tart is a Twirp library for Dart. This is to be used in conjunction with protoc-gen-tart. https://github.com/syncapod/tart 
version: 0.2.0
homepage: https://github.com/syncapod/tart

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies: 
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1

