name: tart
description: Twirp library for Dart
version: 0.1.0
homepage: https://www.syncapod.com/tart

environment:
  sdk: '>=2.15.1 <3.0.0'

# dependencies:

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
dependencies: 
  http: ^0.13.4
